[package]
name = "cgpt"
version = "0.1.3"
edition = "2021"
description = "A command-line ChatGPT client"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
